---
abstract: 'A Catalyst & DBIx::Class powered Wiki.'
author:
  - 'Marcus Ramberg C<marcus@nordaaker.com>'
build_requires:
  Email::Sender::Simple: 0.100110
  ExtUtils::MakeMaker: 6.42
  SQL::Translator: 0.09006
  Test::Differences: 0
  Test::More: 0.88
  Test::WWW::Mechanize::Catalyst: 0.51
  WWW::Mechanize: 1.54
  WWW::Mechanize::TreeBuilder: 1.10000
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MojoMojo
no_index:
  directory:
    - inc
    - t
requires:
  Algorithm::Diff: 1.1901
  Algorithm::Merge: 0
  Archive::Zip: 1.14
  Cache::FastMmap: 1.31
  Catalyst: 5.71001
  Catalyst::Action::RenderView: 0.07
  Catalyst::Authentication::Store::DBIx::Class: 0.101
  Catalyst::Controller::HTML::FormFu: 0.03007
  Catalyst::Model::DBIC::Schema: 0.01
  Catalyst::Plugin::Authentication: 0.10005
  Catalyst::Plugin::Cache: 0.08
  Catalyst::Plugin::ConfigLoader: 0.13
  Catalyst::Plugin::I18N: 0
  Catalyst::Plugin::Session::State::Cookie: 0.11
  Catalyst::Plugin::Session::Store::Cache: 0
  Catalyst::Plugin::Setenv: 0
  Catalyst::Plugin::Static::Simple: 0.07
  Catalyst::Plugin::SubRequest: 0.15
  Catalyst::Plugin::Unicode: 0.8
  Catalyst::View::Email: 0.14
  Catalyst::View::Email::Template: 0
  Catalyst::View::JSON: 0.26
  Catalyst::View::TT: 0.23
  Config::General: 0
  Config::JFDI: 0
  Crypt::CBC: 2.12
  DBD::SQLite: 1.27
  DBIx::Class: 0.08
  DBIx::Class::DateTime::Epoch: 0.04
  DBIx::Class::EncodedColumn: 0
  DBIx::Class::TimeStamp: 0.11
  Data::Page: 2.00
  DateTime: 0.28
  DateTime::Format::Mail: 0
  Directory::Scratch: 0.14
  Encode: 2.31
  File::Copy::Recursive: 0
  File::MMagic: 1.27
  HTML::Entities: 3.60
  HTML::FormFu: 0.02000
  HTML::FormFu::Model::DBIC: 0
  HTML::Strip: 1.04
  HTML::TagCloud: 0
  HTML::Toc: 0
  IO::File: 1.14
  IO::Scalar: 0
  Image::ExifTool: 0
  Image::Math::Constrain: 0
  Imager: 0
  KinoSearch: 0.165
  MRO::Compat: 0.10
  Module::Pluggable::Ordered: 1.4
  Moose: 0
  Number::Format: 0
  Template: 2.20
  Template::Plugin::JavaScript: 0
  Term::Prompt: 0
  Text::Context: 3.5
  Text::MultiMarkdown: 1.000032
  Text::Password::Pronounceable: 0
  Text::Textile: 0
  URI: 1.37
  URI::Find: 0
  YAML: 0.36
  parent: 0
  perl: 5.8.4
resources:
  MailingList: http://n2.nabble.com/mojomojo-f2358427.html
  bugtracker: http://github.com/marcusramberg/mojomojo/issues
  homepage: http://mojomojo.org
  license: http://dev.perl.org/licenses/
  repository: http://github.com/marcusramberg/mojomojo/
version: 1.00
