---
abstract: 'A Catalyst & DBIx::Class powered Wiki.'
author:
  - 'Marcus Ramberg C<marcus@nordaaker.com>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MojoMojo
no_index:
  directory:
    - inc
    - t
requires:
  Algorithm::Diff: 1.1901
  Archive::Zip: 1.14
  Cache::Memory: 0
  Catalyst: 5.7000
  Catalyst::Action::RenderView: 0.07
  Catalyst::Authentication::Store::DBIx::Class: 0.101
  Catalyst::Controller::HTML::FormFu: 0.02000
  Catalyst::Model::DBIC::Schema: 0.01
  Catalyst::Plugin::Authentication: 0.10005
  Catalyst::Plugin::Cache::Store::Memory: 0
  Catalyst::Plugin::ConfigLoader: 0.13
  Catalyst::Plugin::Email: 0
  Catalyst::Plugin::FillInForm: 0.04
  Catalyst::Plugin::FormValidator: 0.02
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::File: 0
  Catalyst::Plugin::Singleton: 0.02
  Catalyst::Plugin::Static::Simple: 0.07
  Catalyst::Plugin::SubRequest: 0.09
  Catalyst::Plugin::Unicode: 0.8
  Catalyst::View::TT: 0.23
  Config::General: 0
  DBD::SQLite: 1.08
  DBIx::Class: 0.08
  DBIx::Class::DateTime::Epoch: 0
  DBIx::Class::EncodedColumn: 0
  DBIx::Class::HTML::FormFu: 0
  Data::FormValidator::Constraints::DateTime: 0
  Data::Page: 2.00
  DateTime: 0.28
  DateTime::Format::Mail: 0
  File::MMagic: 1.27
  HTML::Scrubber: 0
  HTML::Strip: 1.04
  HTML::TagCloud: 0
  IO::Scalar: 0
  Image::ExifTool: 0
  Image::Math::Constrain: 0
  Imager: 0
  KinoSearch: 0
  LWP::Simple: 0
  Module::Pluggable::Ordered: 1.4
  Moose: 0
  Pod::Simple::HTML: 3.01
  String::Diff: 0
  Template::Plugin::JavaScript: 0
  Text::Context: 3.5
  Text::Password::Pronounceable: 0
  URI: 1.35
  URI::Fetch: 0
  XML::Clean: 0
  YAML: 0.36
resources:
  license: http://dev.perl.org/licenses/
version: 0.999022
